config/routes.rb
Sportsleaf::Application.routes.draw do
  resources :games

  resources :pools

  devise_for :users

  get "pages/home"

  get "pages/about"

  get "pages/help"

  root :to => 'pages#home'

  match '*a', :to => 'errors#routing'
end

app/models/pool.rb
class Pool < ActiveRecord::Base
	has_one :manager, :class_name => "User"
	has_many :users, through: :standing

	VISIBILITY = ['Public', 'Private']
	
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController

  # User has to be signed in
  before_filter :authenticate_user!

  
  # GET /pools
  # GET /pools.json
  def index
    @pools = Pool.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pools }
    end
  end

  # GET /pools/1
  # GET /pools/1.json
  def show
    @pool = Pool.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pool }
    end
  end

  # GET /pools/new
  # GET /pools/new.json
  def new
    @pool = Pool.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pool }
    end
  end

  # GET /pools/1/edit
  def edit
    @pool = Pool.find(params[:id])
  end

  # POST /pools
  # POST /pools.json
  def create
    @user = current_user.id
    @pool = Pool.new(params[:pool], :manager => @user)

    respond_to do |format|
      if @pool.save
        format.html { redirect_to @pool, notice: 'Pool was successfully created.' }
        format.json { render json: @pool, status: :created, location: @pool }
      else
        format.html { render action: "new" }
        format.json { render json: @pool.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pools/1
  # PUT /pools/1.json
  def update
    @pool = Pool.find(params[:id])

    respond_to do |format|
      if @pool.update_attributes(params[:pool])
        format.html { redirect_to @pool, notice: 'Pool was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pool.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pools/1
  # DELETE /pools/1.json
  def destroy
    @pool = Pool.find(params[:id])
    @pool.destroy

    respond_to do |format|
      format.html { redirect_to pools_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/pools_helper.rb
module PoolsHelper
end

app/views/pools/_form.html.erb
<%= form_for(@pool) do |f| %>
  <% if @pool.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pool.errors.count, "error") %> prohibited this pool from being saved:</h2>

      <ul>
      <% @pool.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :title %><br/>
  <%= f.text_field :title %>

  <%= f.label :visibility %><br/>
  <%= f.select(:visibility, '<option value="public">Public</option> <option value="Private"> Private </option>') %>
  <%= f.label :description %>
  <%= f.text_area :description, :cols => 30, :rows => 8%>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pools/edit.html.erb
<h1>Editing pool</h1>

<%= render 'form' %>

<%= link_to 'Show', @pool %> |
<%= link_to 'Back', pools_path %>

app/views/pools/index.html.erb
<h1>Your Pools</h1>

<table class="table table-bordered">
  <tr>
    <th>Name</th>
    
  </tr>

<% @pools.each do |pool| %>
  <tr>
    <td><%= pool.title %></td>
    <td><%= link_to 'Show', pool %></td>
    <td><%= link_to 'Edit', edit_pool_path(pool) %></td>
    <td><%= link_to 'Destroy', pool, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pool', new_pool_path %>

app/views/pools/new.html.erb
<h1>Create a pool</h1>

<%= render 'form' %>

<%= link_to 'Back', pools_path %>

app/views/pools/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_pool_path(@pool) %> |
<%= link_to 'Back', pools_path %>