config/routes.rb
Sportsleaf::Application.routes.draw do
  resources :games

  resources :pools

  devise_for :users

  get "pages/home"

  get "pages/about"

  get "pages/help"

  root :to => 'pages#home'

  match '*a', :to => 'errors#routing'
end

app/models/game.rb
class Game < ActiveRecord::Base

	require 'open-uri'
	require 'nokogiri'

	before_create :default_values

	TEAMS = [
		'NY Giants',
		'Philadelphia',
		'Washington',
		'Dallas',
		'Atlanta',
		'New Orleans',
		'Tampa Bay',
		'Carolina',
		'Detroit',
		'Green Bay',
		'Minnesota',
		'Chicago',
		'San Francisco',
		'St. Louis',
		'Seattle',
		'Arizona',
		'New England',
		'NY Jets',
		'Miami',
		'Buffalo',
		'Tennessee',
		'Houston',
		'Jacksonville',
		'Indianapolis',
		'Baltimore',
		'Pittsburgh',
		'Cinncinati',
		'Cleveland',
		'San Diego',
		'Denver',
		'Oakland',
		'Kansas City'
	]

	URL_MAP = {
		'Dallas' => 'http://espn.go.com/nfl/team/_/name/dal/dallas-cowboys',
		'NY Giants' => 'http://espn.go.com/nfl/team/_/name/nyg/new-york-giants',
		'Philadelphia' => 'http://espn.go.com/nfl/team/_/name/phi/philadelphia-eagles',
		'Washington' => 'http://espn.go.com/nfl/team/_/name/wsh/washington-redskins',
		'Arizona' => 'http://espn.go.com/nfl/team/_/name/ari/arizona-cardinals',
		'San Francisco' => 'http://espn.go.com/nfl/team/_/name/sf/san-francisco-49ers',
		'Seattle' => 'http://espn.go.com/nfl/team/_/name/sea/seattle-seahawks',
		'St. Louis' => 'http://espn.go.com/nfl/team/_/name/stl/st-louis-rams',
		'Chicago' => 'http://espn.go.com/nfl/team/_/name/chi/chicago-bears',
		'Detroit' => 'http://espn.go.com/nfl/team/_/name/det/detroit-lions',
		'Green Bay' => 'http://espn.go.com/nfl/team/_/name/gb/green-bay-packers',
		'Minnesota' => 'http://espn.go.com/nfl/team/_/name/min/minnesota-vikings',
		'Atlanta' =>  'http://espn.go.com/nfl/team/_/name/atl/atlanta-falcons',
		'Carolina' => 'http://espn.go.com/nfl/team/_/name/car/carolina-panthers',
		'New Orleans' => 'http://espn.go.com/nfl/team/_/name/no/new-orleans-saints',
		'Tampa Bay' => 'http://espn.go.com/nfl/team/_/name/tb/tampa-bay-buccaneers',
		'Buffalo' => 'http://espn.go.com/nfl/team/_/name/buf/buffalo-bills',
		'Miami' => 'http://espn.go.com/nfl/team/_/name/mia/miami-dolphins',
		'New England' => 'http://espn.go.com/nfl/team/_/name/ne/new-england-patriots',
		'NY Jets' => 'http://espn.go.com/nfl/team/_/name/nyj/new-york-jets',
		'Denver' => 'http://espn.go.com/nfl/team/_/name/den/denver-broncos',
		'Kansas City' => 'http://espn.go.com/nfl/team/_/name/kc/kansas-city-chiefs',
		'Oakland' => 'http://espn.go.com/nfl/team/_/name/oak/oakland-raiders',
		'San Diego' => 'http://espn.go.com/nfl/team/_/name/sd/san-diego-chargers',
		'Baltimore' => 'http://espn.go.com/nfl/team/_/name/bal/baltimore-ravens',
		'Cincinnati' => 'http://espn.go.com/nfl/team/_/name/cin/cincinnati-bengals',
		'Cleveland' => 'http://espn.go.com/nfl/team/_/name/cle/cleveland-browns',
		'Pittsburgh' => 'http://espn.go.com/nfl/team/_/name/pit/pittsburgh-steelers',
		'Houston' => 'http://espn.go.com/nfl/team/_/name/hou/houston-texans',
		'Indianapolis' => 'http://espn.go.com/nfl/team/_/name/ind/indianapolis-colts',
		'Jacksonville' => 'http://espn.go.com/nfl/team/_/name/jac/jacksonville-jaguars',
		'Tennessee' => 'http://espn.go.com/nfl/team/_/name/ten/tennessee-titans'
	}

	#Abbrev Map
	ABBREV_MAP = {
		'Dallas' 	=>	 'DAL',
		'NY Giants' 	=>	 'NYG',
		'Philadelphia' 	=>	 'PHL',
		'Washington' 	=>	 'WAS',
		'Arizona' 	=>	 'ARZ',
		'San Francisco' 	=>	 'SF',
		'Seattle' 	=>	 'SEA',
		'St. Louis' 	=>	 'STL',
		'Chicago' 	=>	 'CHI',
		'Detroit' 	=>	 'DET',
		'Green Bay' 	=>	 'GB',
		'Minnesota' 	=>	 'MIN',
		'Atlanta' 	=>	  'ATL',
		'Carolina' 	=>	 'CAR',
		'New Orleans' 	=>	 'NO',
		'Tampa Bay' 	=>	 'TB',
		'Buffalo' 	=>	 'BUF',
		'Miami' 	=>	 'NE',
		'New England' 	=>	 'NE',
		'NY Jets' 	=>	 'NYJ',
		'Denver' 	=>	 'DEN',
		'Kansas City' 	=>	 'KAN',
		'Oakland' 	=>	 'OAK',
		'San Diego' 	=>	 'SD',
		'Baltimore' 	=>	 'BAL',
		'Cincinnati' 	=>	 'CIN',
		'Cleveland' 	=>	 'CLE',
		'Pittsburgh' 	=>	 'PIT',
		'Houston' 	=>	 'HOU',
		'Indianapolis' 	=>	 'IND',
		'Jacksonville' 	=>	 'JAC',
		'Tennessee' 	=>	 'TEN'
	}
	
	# Set the default value for status to "Open" after creation
	# Update to pending after cutoff time
	# Update to complete after results added
	def default_values
		self.status ||= 'Open'
	end

	def kickoff_time
		start = self.start_date
		ko = self.kickoff
		ko_time = Time.parse("#{start} #{ko}" )
		self.update_attributes(:start_time => ko_time)
	end

	#determines the underdog of the game
	def underdog
	    if home_team != favorite
	        home_team
	    else
	        visitor_team
	    end
	end
	
	#formats underdog and favorite correctly in views (Capitalizes if home team)
	def index_favorite
		if home_team == favorite
	        home_team.upcase
	    else
	    	favorite
	    end
	end

	def index_underdog
		if home_team == underdog
	        underdog.upcase
	    else
	    	underdog
	    end
	end

	def self.process_score
		fav = self.favorite_score
		dog = dog.underdog_score

		net = fav - dog
		if net == line
			self.update_attributes(:cover => "PUSH")
		elsif net > line
			self.update_attributes(:cover => "FAVORITE")
		else
			self.update_attributes(:cover => "UNDERDOG")
		end
	end

	def self.matchup_stats(team)
		url = URL_MAP[team]
		doc = Nokogiri::HTML(open(url))

		# Fetch stats. # 1 =>Pass yd # 2 =>Rush Yards # 3 =>Opp Pass Yards# 4 => Opp Rush Yards
		yards = []
		ranks = []

		# Fetch raw yardage for cats
		doc.css("div.mod-content > span").each do |h|
			yards << h.text
		end

		#fetch NFL ranks for each stat
		doc.css("div.mod-content > strong").each do |h|
			ranks << "(#{h.text})"
		end

		stats = yards.zip(ranks)
		stats.each.map do |s|
			s.join ' '
		end
	end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :authenticate_user!
  # GET /games
  # GET /games.json
  def index
    @week = 9
    @games = Game.where(:week => @week)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(params[:id])

   # @home_stats = Game.matchup_stats(@game.home_team)
    # @visitor_stats = Game.matchup_stats(@game.visitor_team)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(params[:game])

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :week %><br />
    <%= f.number_field :week %>
  </div>
  <div class="field">
    <%= f.label :home_team %><br />
    <%= f.text_field :home_team %>
  </div>
  <div class="field">
    <%= f.label :visitor_team %><br />
    <%= f.text_field :visitor_team %>
  </div>
  <div class="field">
    <%= f.label :favorite %><br />
    <%= f.text_field :favorite %>
  </div>
  <div class="field">
    <%= f.label :line %><br />
    <%= f.text_field :line %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :kickoff %><br />
    <%= f.text_field :kickoff %>
  </div>
  <div class="field">
    <%= f.label :favorite_score %><br />
    <%= f.number_field :favorite_score %>
  </div>
  <div class="field">
    <%= f.label :underdog_score %><br />
    <%= f.number_field :underdog_score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h2>Current Lines</h2>
    <br/>

    <table class="table table-bordered table-condensed table-striped" width="50%" style="text-align: center;">
    <thead>
      <tr>
        <th> Day </th>
        <th>Kickoff </th>
        <th>Home </th>
        <th>Visitor </th>
        <th>Selection</th>
        <th>Star Pick? </th>
        <th>Game Details</th>

      </tr>
    </thead>
    <tbody>
        <% @games.each do |game| %>
          <tr>
            
            <td><%= game.start_date %> </td>
            <td><%= game.kickoff %> </td>
            <td><%= game.home_team %></td>
            <td><%= game.visitor_team %> </td>
            <td><%= select_tag "selection", options_for_select([["#{game.home_team}"], ["#{game.visitor_team}"]]), :style => "width: 100px;", %></td>
            <td><%= check_box_tag "star_pick", :style => "float: right;" %></td>
           
           
            <td>
                <%= link_to 'Details', game, :class => "btn btn-primary btn-inverse" %> 

            <% if can? :update, game %>
                <%= link_to 'Edit', edit_game_path(game), :class => "btn " %>
            <% end %>
                
            </td>

        </tr>
        
        <% end %>  

    </tbody> 
    </table>

    <br />

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>


      <div class="game_details">
        <h3><%= @game.visitor_team %>   at   <%= @game.home_team %>  </h3>
          <h4> <%= @game.start_date.strftime("%B #{@game.start_date.day.ordinalize},"+' %Y')  + " @ #{@game.kickoff} " %> </h3> <br/>
          
         <span> <h4><span class="orange"> Favorite: </span><%= "#{@game.favorite}(-#{@game.line}) " %>   </h4>
          
       <div id="game_matchup">
          
          
          <h3><strong> Matchup </strong></h3>
          <table class="table  table-bordered table-striped table-condensed matchup" style="width: 60%;">
            <thead>
              <th>Category</th>
              <th><%= @game.visitor_team %></th>
              <th><%= @game.home_team %> </th>
            </thead>
            <tr>
              <td><strong>Rushing YPG</strong></td>
              <td></td>
              <td></td>
            <tr>
              <td><strong>Opp Rushing YPG</strong></td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <td><strong>Passing YPG</strong></td>
             <td></td>
             <td></td>
            </tr>
            <tr>
              <td><strong>Opp Passing YPG</strong></td>
             <td></td>
             <td></td>
            </tr>
          </table>
        </div>
        
        
         
          <br/>
          
     
            <p><%= hidden_field(:game_id, @game.id) %></p>

        
              
              <br/>
              <% if can? :update, @game %>
                <%= button_to "Results for this game", new_result_path, :class => "btn btn-primary", :method => "get"  %>
                <%= link_to 'Edit', edit_game_path(@game) %> 
              <% end %>
            <%= @message %>
            
        </div>

  



    


  